files:

  - source: "/priv/gettext/default.pot",
    translation: "/priv/gettext/%two_letters_code%/LC_MESSAGES/default.po",

  - source: "/priv/gettext/errors.pot",
    translation: "/priv/gettext/%two_letters_code%/LC_MESSAGES/errors.po",
