version: '2.4'

x-app:
  &app
  build:
    context: .
    dockerfile: ./Dockerfile
    args:
      PG_MAJOR: '14'
      NODE_MAJOR: '16'
      YARN_VERSION: '1.13.0'
  environment:
    &env
    MIX_ENV: development
  # image: chaskiq/chaskiq:1.1.0
  tmpfs:
    - /tmp

x-backend:
  &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - .:/app:cached
  environment:
    <<: *env
    DATABASE_URL: postgres://postgres:password@postgres:5432
    EDITOR: vi
  depends_on:
    postgres:
      condition: service_healthy

services:
  runner:
    <<: *backend
    command: /bin/bash

  phoenix:
    <<: *backend
    command: mix phx.server
    ports:
      - '4000:4000'

  postgres:
    image: postgres:14-alpine
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      #POSTGRES_USER: postgresql
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PSQL_HISTFILE: /root/log/.psql_history
    ports:
      - 5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

volumes:
  postgres: null
